apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mi-aplicacion-clima
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mi-aplicacion-clima
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
